### ISSUE TITLE
"gotta-go-fast: Prelude.!!: negative index" error on paragraph mode

### ISSUE THREAD

**Issue by MauricioRobayo** [callum-oakley/gotta-go-fast#15]
Hi! `gotta-go-fast` is great, thanks for putting it out there!

I'm getting an error on `paragraph mode`:

```
$ gotta-go-fast -p README.md
gotta-go-fast: Prelude.!!: negative index
```

It's the same error if I use:

```
$ gotta-go-fast -prw 60 README.md
gotta-go-fast: Prelude.!!: negative index
```

I have tried with this [READEME.md](https://github.com/MauricioRobayo/gogofast#readme) and with [this text](https://gist.github.com/MauricioRobayo/7b6c3c882c168b28536c368ba8eef411).

**Comment by callum-oakley** [comment]
What version are you on? (`--version`)

It looks like you are hitting a bug that was [fixed in version 0.3.0.4](https://github.com/callum-oakley/gotta-go-fast/commit/6edec80ac47bad8843387eb1ce2579cd1888b488). There was an error if you tried to use paragraph mode on a file without any paragraphs of suitable length (configurable with `--min-paragraph-len` and `--max-paragraph-len`), but since 0.3.0.4 it just falls back to sampling lines in that case.

Let me know if updating doesn't solve it!

P.S. gogofast looks like a great idea. :)

**Comment by callum-oakley** [comment]
I just realised I never updated the binary release, so if you downloaded a binary instead of installing from source you're probably on 0.3.0.1... ~I'll push a new release now.~ done 😅

**Comment by MauricioRobayo** [comment]
Thanks! Yes, indeed I was using a previous version:

```
$ gotta-go-fast --version
Gotta Go Fast 0.3.0.1
```

I built it from source since there is no Linux binary on the latest release, working as expected.
