### ISSUE TITLE
Red frame obscures text

### ISSUE THREAD

**Issue by ygale** [callum-oakley/gotta-go-fast#4]
The red frame around the sample text, as shown in the image in the README, only appeared after I made my first mistake. When it appeared, it obscured the last letter on the longest line. This happened while running `gotta-go-fast README.md`, and it obscured the letter `e` at the end of this line:

    Pass `gotta-go-fast` the name of a file, and it will extract a random 20 line

**Comment by ygale** [comment]
Using version 0.1.2.0, built from git commit `11e626449ce746f432e52c4b2ac3bcfe0e1b866a`, on Mac OS X 10.10.5, using `stack install`.

**Comment by callum-oakley** [comment]
Interesting! The red frame should indeed only appear after the first mistake (it's to make it obvious that you have a mistake so you know you have to go back and correct it) but it certainly shouldn't obscure the text! Any chance you could take a screenshot so I could see this in action?

**Comment by callum-oakley** [comment]
Ah, on second thoughts, I think this is probably just due to the width of your terminal. I'm not currently wrapping text based on the terminal width, I'm just wrapping everything to 80 characters. However if this is too wide you can tweak it with the `--width` (or `-w` option). Let me know if this helps! It would certainly be good to wrap based on terminal width in the future... I'll put it on the backlog ;)

**Comment by callum-oakley** [comment]
The frame is removed entirely in the latest version.
