### ISSUE TITLE
No WPM and accuracy report

### ISSUE THREAD

**Issue by ygale** [callum-oakley/gotta-go-fast#5]
When I finished typing the sample text, I didn't get a "WPM and accuracy report". It just stopped. The only thing I found I could do was Ctrl-C to quit.

Actually it would be a nice feature to have a running WPM and accuracy report at the bottom of the window as I type. Would that be hard to do?

Using version 0.1.2.0, built from git commit `11e626449ce746f432e52c4b2ac3bcfe0e1b866a`, on Mac OS X 10.10.5, using `stack install`.

**Comment by callum-oakley** [comment]
I suspect that this is because you still had errors! I should make this clearer in the readme, but you aren't finished until you've corrected all of the errors ;) You only get the final report when all the text is typed with no errors (you can backspace to correct things).

I'd personally rather not have a running WPM and accuracy, because I think I would find it distracting, but I would consider adding it as an option if there was demand – it wouldn't be *too* hard. Thanks for the suggestion!

**Comment by deepredsky** [comment]
I was confused by this too, it think it will be a good idea to add a note in readme

**Comment by callum-oakley** [comment]
Good idea, thanks for the suggestion!

**Comment by callum-oakley** [comment]
The usage section in the readme is updated to hopefully make this clearer now.
